port: 8047
juju-addrs: ["jimm.jujucharms.com:443"]
log-level: debug
image-name: termserver
lxd-socket-path: /var/snap/lxd/common/lxd/unix.socket
profiles: ["default"]
session-timeout: 2
welcome-message: |
  Welcome to JAAS insecure jujushell!
  This is an example welcome message.
