port: 8047
juju-addrs: ["jimm.jujucharms.com:443"]
log-level: debug
image-name: "termserver"
profiles: ["default"]
session-timeout: 20
tls-cert: |
  -----BEGIN CERTIFICATE-----
  MIIFezCCA2OgAwIBAgIJAKHprWndysgcMA0GCSqGSIb3DQEBCwUAMFQxCzAJBgNV
  BAYTAkdCMQ0wCwYDVQQIDARKdWp1MQwwCgYDVQQHDANHVUkxDzANBgNVBAoMBlVi
  dW50dTEXMBUGA1UEAwwOYWFhLnVidW50dS5jb20wHhcNMTcwOTI3MTU1MDI5WhcN
  MTgwOTI3MTU1MDI5WjBUMQswCQYDVQQGEwJHQjENMAsGA1UECAwESnVqdTEMMAoG
  A1UEBwwDR1VJMQ8wDQYDVQQKDAZVYnVudHUxFzAVBgNVBAMMDmFhYS51YnVudHUu
  Y29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAviGilp498mYXzvad
  0pO+YjMVl/p+1LdiKqPIycbuzEEPaQjQWMdwX3/qTzc8PpwEbJ3bwxPPNHJoAFev
  wCbct0+DKds2H9mSMjGZq1Fc2RVnDdOJzZDGr26zOiwKynRo1PbqxBkBF4Bo+Ab/
  0Iy434G7jyQgtvRX+Xl9CJwKjUfp90/je5Q6rSyb30mZotEjARlaSoynLS817nQx
  bB8aTUxY1w2X74H2oLIeisGQ5k0lNjHAi8S7529sQHM/GiggQLpUHUj4QgwKyr7K
  b441S26LQmXG/Rvoce1wmPTrQS9ubYhv8vWUvXlpM/mlxqnqYLmH+M1f2m4lhk4P
  gHXRnfK4xgws/Okd1NadqLfTVd0T8iNORyh8cGOBZxjTj7in2EXsJ55Tk8nkzbay
  5/CCtsrviVOoCntNBlzFu+IyDZBsDrryRbTCARxk/zRdHmNjusi9MobQnDGzb4uJ
  ctN9QK7Hd4zxz6HgJAmhazgMUQ06cqVQuAXAqZeZF7xiAtp8DOqOLWaTGO31xZ47
  pZnHmLY7Fgr2Xb53JCaSugi0Ydl76H4AkRmPd80+WRoAslBeBdGsDwu5B7wUbMHD
  RdHZ2q4U1Y7uj0ASAQC/fM9dhfaHF+841thlRfn/XaZnNx19G6wLOGV4pQ7agkY+
  XSlqT3bcOaV9RLgUn9y3EqHQrFMCAwEAAaNQME4wHQYDVR0OBBYEFKYDZIIJsgre
  fpk6ioUasB3qZpEYMB8GA1UdIwQYMBaAFKYDZIIJsgrefpk6ioUasB3qZpEYMAwG
  A1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAEimWgeHPnim7tfGaC15hea6
  ovCZ3sIzmLQB33+YJ+crFHIwlIuWLFpe7tj9bgmhmTHZ0tWJzX2wBhMR38Yy7c1F
  KEgVNbM5mswP2XKoETOwxuyxgYqQ7p6IrEBKVsNBOL4HRopS9ezDAaeT7KnP1RY6
  A/9kN8ixzo4kW9GHU3g1KeKmuT3N+ttvk5mj8Mx+gCtXSyOz9lS8iSVoLuFjYB93
  BpUobcIJBv2ETwOYilaYuIsvWR5nr5nJ15qx1iuJ4OVS1un+9up5QqToziyL9x4H
  LZJ3yiqBmH4OwFOKV60rOQa+Q4kaSxruRyZpLoMhl+IKDVueyBMoLfDx4rFrODpj
  c5beQvH8V9ej8ft/7Jl7dr80b+fV9sC0AsOJWYhtqdQQbuoZWlJ5qqngcJdYVRai
  X1E4pp915EpKvib8R1nNZRGIL8mDpFwLtWQER2gKQy11vc75lFPARmFl+TXCVoNS
  wObwu1+qYNYm1pZOnZOJ4jVb3pg9nYV9fBYEgbH77JU3LLE7e5PW1Yo2j5BH3NyJ
  BwZHCVE3574yVGxRm+Y3HSpIUNBo2ZO47W4pTYvGs79hp6vtCe0ffZJKdTW7sDmS
  JqOLZW5+rMtAkF34PP0tXmJo1/Xp9vhi+tYs5a0eNeOiAdbu08q0fnUxOEGCncH8
  s268+BkOPpPlDMiRoEfI
  -----END CERTIFICATE-----
tls-key: |
  -----BEGIN PRIVATE KEY-----
  MIIJRQIBADANBgkqhkiG9w0BAQEFAASCCS8wggkrAgEAAoICAQC+IaKWnj3yZhfO
  9p3Sk75iMxWX+n7Ut2Iqo8jJxu7MQQ9pCNBYx3Bff+pPNzw+nARsndvDE880cmgA
  V6/AJty3T4Mp2zYf2ZIyMZmrUVzZFWcN04nNkMavbrM6LArKdGjU9urEGQEXgGj4
  Bv/QjLjfgbuPJCC29Ff5eX0InAqNR+n3T+N7lDqtLJvfSZmi0SMBGVpKjKctLzXu
  dDFsHxpNTFjXDZfvgfagsh6KwZDmTSU2McCLxLvnb2xAcz8aKCBAulQdSPhCDArK
  vspvjjVLbotCZcb9G+hx7XCY9OtBL25tiG/y9ZS9eWkz+aXGqepguYf4zV/abiWG
  Tg+AddGd8rjGDCz86R3U1p2ot9NV3RPyI05HKHxwY4FnGNOPuKfYRewnnlOTyeTN
  trLn8IK2yu+JU6gKe00GXMW74jINkGwOuvJFtMIBHGT/NF0eY2O6yL0yhtCcMbNv
  i4ly031Arsd3jPHPoeAkCaFrOAxRDTpypVC4BcCpl5kXvGIC2nwM6o4tZpMY7fXF
  njulmceYtjsWCvZdvnckJpK6CLRh2XvofgCRGY93zT5ZGgCyUF4F0awPC7kHvBRs
  wcNF0dnarhTVju6PQBIBAL98z12F9ocX7zjW2GVF+f9dpmc3HX0brAs4ZXilDtqC
  Rj5dKWpPdtw5pX1EuBSf3LcSodCsUwIDAQABAoICAQC9YgVwX5i2nQi0ByQ2/yEQ
  8W9d3Y591Vg7vr6edb+gxmFSLwxQkf+VsHU0iIFCn+csRaUDz/SBej+rr6wJCuyo
  ztOIWqiz2uTriEpXwgho1w+6Tu4hS0cMsYhmtj3dYUyWbIh14a4bubVU8KvZEIKJ
  ZtDrCIJpmkMS5PctHzjHd01OIU4m5wP3QMrWA5q7+fMTAizUuvs+X5sptKUR3H03
  Z4fKVej0EZEWibUwYxQwwcECFVaEIedE5NB/9gtxw2w07SQhs3BNYW9See5sZcsi
  Iq8l6PjnXugOqwKP6M14NYWaJt/TstiATrICqnV8x/0EcWlF41PJ4BMSjyiTvUeX
  g/LOg3vqXkSnOwEX1a4Vl1F/NjevyicJ5J2KHpKPQLeUv/ZW/AzZbBhUN7n8O1J4
  w6Lad+ENnifQyWfDWVZfazzyE6IPOlcTTW02CflFcrXitcDWFV/sf9MCucLgpokq
  cf6xGtPxRhAgdoiEG6J3N8nFvKJtfE5SLTKEBAlPlcvxVIHaNVDgflJejKmNmQIC
  Dcs8//VvN8JEhdfrb3kSB8QBmf4mqXVnGspuvtSK7l8CGYNARy/t8OIYoBfXoylc
  QP7nx0cYTkf8bftwFHOdYexb/ARmbpFPyiB/pImSi3bgbEaTLqJ1wwx/PyIeFQfG
  RauaWxFWGl32vxt12fryKQKCAQEA4XzbQWH71JGx5ErxPoSnu5AhY3WM1QFgJ/CP
  U2vyow7jxDRLSaUJ57j2N46m8lQcJ8XB/bCDQNCgUS22SNspSJ35NMte4cYj/Dl6
  PoEFUMFXREbwpQPmg06WkfhvVSQEWAB5WxgDD1k7Jc4SRXLeDIEX93QMsQxLP4Q+
  9x7sagbdLlQ7R9++sVSMpMCDKxtRTWt/eSjVKOEpyyxKaoczwd+AhIxUaYOZC+wx
  c85/fxnrMsa9eNrSZokPhSQ0f3jClpRp+xj/fC1FGyYMOAONY/Y2Earm8JS7einD
  VaLiHqAOnt9y7Hdb5CVMlObPzVD3yVf7H/7T8zs7afoZpYrYdwKCAQEA19v/CNLZ
  GjrR0Dcm9nVmu28/kmMxUxrbmxRMAPq99lO6ivwS3QmX0jgTd0orGOS3X+ej1Zgh
  9p3UqmzslB7uWExG5SMfKyYR2poqku96GxCEqBd65dO+3t8BDwj2f+P3oaQC+iHQ
  xLvpktoUEEuwFcqDYVCop0h2iNkclsscX05wtgGEwb3yD9lngSk99b9GawOB5dp6
  ZyfhjGIrDfPjEnYzQIbVtAzTJnorSJTuLHCx6kKgdJ6iYjUKEO++lVBKzw+Jeqts
  4X8pN2CriaOCkI8gMcATyt++Z4DjgDO8wP2DwS99v8q0+m58ZbE+L3euFNARnb4X
  f4a7WejXEMeeBQKCAQEAuCYRobn1wkoiL8EMd/Q6T7GLswBDPYncD4IkawqTo5r7
  ZDcY7VH9XuLtIb48lVcfj1Ov9BD9gCdhZiqg3asucgGhjf4wxM3egZQnQ3h28NaV
  AEu3J+yhisbZrOhpc+zwJzZr5XsctKI47cz3mwQOV8Pt4MdDviu+IGdOTN9ST9y/
  MaDUsQQHZicYnUwjU0cCBOovtrEkNDh+u1C2jX1RRZnUCWvZXDp++P+x+1O/R/vQ
  2yz3fAWpItf4dtF0lk33DKa0Tr7Bl5YZA+z0uaIdDG/9BDzAUeYFneURg5R8empY
  xmLSJk/sGcxkWI6PUqw3UJWrnxur2M6c3RXFcC6OTQKCAQEAwE5cTW4awIV6erdH
  3PYGyiF4T2BThyg8UVKpy42XQyag4EVmQMnVGhGfNf07m/fXbnedvCLGz0EZP6O+
  uM89pCiAWI8Lq5NFAK2sFC+JZyc2J9KTSMF2IHQoK07e3F0qNjU5+cG6jiqjEpN6
  oHHts9wxY7dKKY4jHBPgpm7ZHgdx3pRHw5sHVhtnXOhzLMZ1Y81CIpabyd77z+d9
  V/bZa48mZew54ygxzOu2N/mGnszflEY7UOoq3LdH+oK8FaXsn7/FySWD4Pk6rP1Q
  lVS4czUvh2MJvwnKRcfL5mExXfX9NVSsAPwEc7+Oz8IyFnPXAO/FYfUCVjigHJ+V
  SnusSQKCAQEAqnr5dIQ+rFybvQQKXnfE0V1M2lpvAliZtYkZ1gfBO26kwzf1lwzl
  XloMEaS6R0cGrc+DYRvChzBETPiw0kH091kD/ZF8gQBekKhZHvo8WdUd8T+DS8H2
  uWGcN6J5b0yAId+L1gH9rW/zAzGkG5ba00PofbbnV6IjciI77HlEcqkc3J5TaDUt
  1dRbUpXsAGXZiy2fAVL68squTDSPdX/BlOBeaVCRpONbTg9zY3abhdMJ5jRn4fNZ
  4sPdiZvu3TpcySGMiWBIBFwg1oKgif1oxONwKKqGsS1h+lJ2ejPQ2qQkdLTeKTnz
  43CbdD4VeC4VsMubOCjbT24bBdcU0CbjeA==
  -----END PRIVATE KEY-----
welcome-message: |
  Welcome to JAAS jujushell!
  This is an example welcome message.
