port: 8047
juju-addrs: ["10.0.42.81:17070"]
log-level: debug
image-name: "termserver"
juju-cert: |
  -----BEGIN CERTIFICATE-----
  MIIDrDCCApSgAwIBAgIUbkXNpIa03OZqEEo+8oruxwgT2YAwDQYJKoZIhvcNAQEL
  BQAwbjENMAsGA1UEChMEanVqdTEuMCwGA1UEAwwlanVqdS1nZW5lcmF0ZWQgQ0Eg
  Zm9yIG1vZGVsICJqdWp1LWNhIjEtMCsGA1UEBRMkOGExODczYjAtM2E4OC00YmQy
  LTg0MGUtOTZjMzI0NDZlNTk0MB4XDTE3MDkxNjA5MjEzN1oXDTI3MDkyMzA5MjEz
  NlowbjENMAsGA1UEChMEanVqdTEuMCwGA1UEAwwlanVqdS1nZW5lcmF0ZWQgQ0Eg
  Zm9yIG1vZGVsICJqdWp1LWNhIjEtMCsGA1UEBRMkOGExODczYjAtM2E4OC00YmQy
  LTg0MGUtOTZjMzI0NDZlNTk0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
  AQEAsHoUGUOrfn6VDHsu2UeG0AV9pe/Lk4anhv1V49sEz8wAwlJVZsUB8dLBHUoe
  +BFCzhRkbSrY4bqeXOd1N0eaZdUmMTXUfmytum8ihuzTttPQp7RF3facDqk2RXbk
  wEPRzkaDnhMhO8aSCFhf2z6auMFttJRUxgkYzfPwW5+18RhnZkWLAmju1WeGJB3Z
  6nyWL4FuQeziTEEMOj7CyYfaYnjVGTZBzfBzu1Pg+FIOcKpi9rnkUwt44BgUPnN4
  d8mkEmIJOZfoiVCwQvujXDoWMXp7bsAKvNA3v49viYj/p4VAlbxHFDQqa+t9Ns0p
  xTEVp5ViPd8LqnME8s1j2YVZUwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
  VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUxlHsNOL6Fkrpsh0c5OOohiY0Aw4wDQYJ
  KoZIhvcNAQELBQADggEBAHqH7z4N0z9EVCsuonIkM5wgHExcK/b9FkGT7on3folX
  LhNy495z1+xyVtHhg3bi0SMMpTxXzV72ViNPGS0NrVEcRJStLJXlhMvgBdb6gfgu
  jeUNYXepWqiY+/rXQiNOKIFQZxFcAuM74vVLiv4v1CwcmmIVMc97c3SgH0wbbPw3
  7c+7CJmDs03myqyAnPY5xrd5eSzixRROCcYCOeSWvY+KwCYMYYD+9kXKFHYvCE3S
  5rQdtqY6rvslMK0HBimNU37PeqImqlFWkieTfQR1xhclsbQspqAsziPXK3Y2Ztt/
  KuObIrXcjq1LbNVfx/zZepyjHRJTiKrd08oCK7tZtgk=
  -----END CERTIFICATE-----
